# Cluster configuration
flink.dir: /home/experiment/wj2/env/flink-1.11.0
# Configure the master node of yarn: port
yarn.ip.port: http://slave033:8088
ip: 0.0.0.0
query.distance: 5s
job.listen.distance: 5s
# Configure the local Prometheus ip: port
prometheus.ip.port: http://slave033:9090
# Pushgateway installation directory
pushgateway.dir: /home/experiment/wj2/env/monitor/pushgateway-1.2.0.linux-amd64

# Determine stream task or batch task
flink.job.type: batch

# stream task stabilization time
stream.stable.time: 10min
# Stream job interval sampling time period
stream.listen.distance: 1min
# Number of samples after the stream job is stable
stream.sample.times: 3

# The configuration of user and keytab is in the .bashrc|| .profile || .bash_profile file
# krb5Location is the krb5.conf file in the same directory as keytab
kerberos:
  user: #FL_user
  keytab: # <path>
  krb5Location: # <path>

# Performance metrics weight
metrics:
  flink_taskmanager_Status_JVM_Memory_Heap_Used/(flink_taskmanager_Status_JVM_Memory_Heap_Committed-134217728): 0.1
  flink_taskmanager_Status_JVM_Memory_NonHeap_Used/flink_taskmanager_Status_JVM_Memory_NonHeap_Committed : 0.2
  flink_taskmanager_Status_JVM_CPU_Load: 0.1
  flink_taskmanager_Status_Network_AvailableMemorySegments/flink_taskmanager_Status_Network_TotalMemorySegments : 0.2
  time: 0.4
  #latency: 0.2
  #consumption.ratio: 0.2

#flink parameter
parameters:
  taskmanager.memory.process.size: [1g,2g,3g,4g,5g,6g,7g,8g,9g,10g,12g,14g,16g,18g,20g]
  taskmanager.numberOfTaskSlots: [1,2,3,4,5,6,7,8,9,10,11,12]
  taskmanager.memory.network.fraction: [0.05,0.1,0.15,0.2]
  taskmanager.memory.managed.fraction: [0.3,0.4,0.5,0.6,0.7]
  parallelism.default: [1,2,4,6,8,10,12,14,16,18,20,24,28,30]



# Performance target
target: 0.8
# Stream job
#j ob.submit.cmd: ./bin/flink run -m yarn-cluster /home/experiment/wj2/env/yinhan_jars/kafka2flink_new.jar
# sqljob
job.submit.cmd: ./bin/flink run -m yarn-cluster -c org.apache.flink.benchmark.Benchmark /home/experiment/wj2/project/flink-sql-benchmark-master/flink-tpcds_2020_12_09/target /flink-tpcds-0.1-SNAPSHOT-jar-with-dependencies.jar --database tpcds_bin_orc_10 --hive_conf /home/experiment/wj2/env/apache-hive-2.3.4-bin/conf --queries q9.sql
# job.submit.cmd: ./bin/flink run -m yarn-cluster -c org.apache.flink.huawei_sql.test /home/experiment/wj2/project/flink-sql-benchmark-master/flink-tpcds/ target/flink-tpcds-0.1-SNAPSHOT-jar-with-dependencies.jar --database huawei_1 --hive_conf /home/experiment/wj2/env/apache-hive-2.3.4-bin/conf
# standalone cluster yarn-cluster
job.submit.pattern: cluster

memory.slot.min: 0.5g
memory.slot.max: 2g
taskmanager.memory.network.min: 256m
taskmanager.memory.network.max: 4096m
time.reduce.ratio: 0.3
max.latency: 1s
consumption.target: 200000
genetic.iteration.max: 5
max.degenerate.count: 3